### ISSUE TITLE
Form elements do not have associated labels

### ISSUE THREAD

**Issue by Samuel-Akin** [VerisimilitudeX/DNAnalyzer#277]
I tried to analyze your website using Lighthouse an realize the toggle button does not have an _associated label_,  I'd like to fix this

![Screenshot 2022-10-28 095301](https://user-images.githubusercontent.com/108809796/198547169-b328849f-3140-456b-9dd8-675e91f62c9b.jpg)

**Comment by LimesKey** [comment]
You can try to fix this, @krishnabiradar310802 created the website so they can help too.

**Comment by Verisimilitude11** [comment]
@Samuel-Akin how far are you on this issue? Feel free to take more time if necessary. I would appreciate it if you could star this repository to show your support if you haven't done so already. If you have any questions, please join our Discord server: https://discord.gg/X3YCvGf2Ug.

**Comment by Verisimilitude11** [comment]
@Samuel-Akin are you still interested in working on this?

**Comment by Verisimilitude11** [comment]
Alright, sounds good. Let me know if you need any more help with this issue.

**Comment by Verisimilitude11** [comment]
Hi there,

I hope this message finds you well. I noticed that it has been over a month since you last contributed to the DNAnalyzer project, and I wanted to check in with you to see if you are still interested in being a part of the team.

If you are still interested in working on DNAnalyzer, please let me know and we can discuss how you can get re-involved with the project. If you are no longer interested, I understand and will unassign you from the project for now. However, if you change your mind and want to get involved again in the future, please don't hesitate to reach out – I'll be happy to add you back to the team.

Thank you for your previous contributions to DNAnalyzer, and I hope to hear back from you soon.

Best,
@Verisimilitude11

**Comment by Verisimilitude11** [comment]
@Samuel-Akin any updates?

**Comment by Lyndsayfutrell** [comment]
I'd like to work on this issue!

**Comment by Verisimilitude11** [comment]
Sounds good! I assigned it to you.
