### ISSUE TITLE
Add support drag&drop in GUI

### ISSUE THREAD

**Issue by frankschmitt** [VerisimilitudeX/DNAnalyzer#296]
The GUI should support drag&drop of DNA files (and possibly protein files). See also https://github.com/Verisimilitude11/DNAnalyzer/pull/286

**Comment by frankschmitt** [comment]
@Verisimilitude11 You can assign this issue to me if you like.

**Comment by Verisimilitude11** [comment]
Assigned.

**Comment by Verisimilitude11** [comment]
@frankschmitt just checking in - how far are you on this issue?

**Comment by frankschmitt** [comment]
@Verisimilitude11 I haven't had the time to start on it yet. Hopefully, I'll get around to it in the next couple of weeks.

**Comment by Verisimilitude11** [comment]
@frankschmitt Alright sounds like a great plan. Thanks for working on this!

**Comment by Verisimilitude11** [comment]
Hi @frankschmitt,

I hope this message finds you well. I noticed that it has been over a month since you last contributed to the DNAnalyzer project, and I wanted to check in with you to see if you are still interested in being a part of the team.

If you are still interested in working on DNAnalyzer, please let me know and we can discuss how you can get re-involved with the project. If you are no longer interested, I understand and will unassign you from the project for now. However, if you change your mind and want to get involved again in the future, please don't hesitate to reach out – I'll be happy to add you back to the team.

Thank you for your previous contributions to DNAnalyzer, and I hope to hear back from you soon.

Best,
@Verisimilitude11

**Comment by frankschmitt** [comment]
Hi @Verisimilitude11,

> I hope this message finds you well. I noticed that it has been over a month since you last contributed to the DNAnalyzer project, and I wanted to check in with you to see if you are still interested in being a part of the team.

Thanks for asking. To be completely honest, I'm too busy to contribute to DNAnalyzer at the moment. Feel free to unassign me, and I'll reach out in the future when my schedule allows contributing again.

Kind regards
Frank

**Comment by Verisimilitude11** [comment]
Hi @frankschmitt,

Thank you for your reply. I understand that you are busy at the moment and may not have the time to contribute to DNAnalyzer. If your schedule opens up in the future and you want to get involved again, please don't hesitate to reach out – we'll be happy to have you back on the team.

I appreciate the work you have done on DNAnalyzer so far, and I hope to see you back on the project when you have the time and energy to contribute again. In the meantime, if you have any questions or need any help, don't hesitate to reach out.

Best,
@Verisimilitude11
