### ISSUE TITLE
Complementary DNA sequence

### ISSUE THREAD

**Issue by VerisimilitudeX** [VerisimilitudeX/DNAnalyzer#306]
This feature will help us to identify transcription factors. Here are the specifications of this issue:
1. Duplicate the DNA sequence
2. Find all occurrences of 'A' and change it to 'T'
3. Find all occurrences of 'T' and change it to 'A'
4. Find all occurrences of 'G' and change it to 'C'
5. Find all occurrences of 'C' and change it to 'G'
6. Return the DNA string

You're not required to know this, but if you're interested, you might find this helpful: https://heimduo.org/what-is-the-complementary-dna-sequence/#:~:text=Complementary%20sequence%3A%20Nucleic%20acid%20sequence%20of%20bases%20that,What%20is%20the%20sequence%20of%20its%20complementary%20strand%3F

**Comment by LimesKey** [comment]
Is this related to detecting gene redundancy by cutting out the complementary DNA sequence in order to increase performance?

**Comment by Verisimilitude11** [comment]
No, this is more involved with new features (for example, the one that Karzinisierung was talking about). I added a description to the issue to clarify it.

**Comment by LimesKey** [comment]
> how far are you with the removal of the headers in FASTA files? I can take over if you want to focus more on the DIAMOND integration.

I've taken a small break because I'm having trouble finding a few reference files from a variety of different sources to try to create a universal program to do this. I should try contacting that Google-Fuu wizard in the discord, maybe he can help.

Feel free to help at all, I'll continue working on it but if you have a solution you can for sure add it. I'm going to try to update the Github Projects section a bit more with some new information and just to keep me organized.

> for example, the one that Karzinisierung was talking about
Can you link me this?

Like you know, I'm doing the CS50X course so I'm going to be slightly more busy than normal and once I'm done I'll have a lot more knowledge to help this project further.
