### ISSUE TITLE
DNA -> RNA

### ISSUE THREAD

**Issue by VerisimilitudeX** [VerisimilitudeX/DNAnalyzer#60]
Find all occurrences of the `T` nucleotide and convert it to `U`. The user would give an additional command line input through the CLI, which would need to be updated as well.

**Comment by Speedro** [comment]
Hi, could you provide more info to this? Thanks

**Comment by Verisimilitude11** [comment]
Hi @Speedro, thanks for your interest in contributing to the world of open source! This issue has already been claimed by someone else for Hacktoberfest. However, the developer team would really appreciate your help in issue https://github.com/Verisimilitude11/DNAnalyzer/issues/19. If you are interested in this, let me know so that I can give you an overview of what work needs to be done for it. To get started, navigate to our GitHub repository: https://github.com/Verisimilitude11/DNAnalyzer and fork it. Take some time to read the documentation and to acquaint yourself with the code. Thanks again for contributing, we at DNAnalyzer really appreciate your time and help!

**Comment by Speedro** [comment]
Hi @Verisimilitude11 thanks for your reply. I've went through the code base. I will gladly help with mentioned [issue](https://github.com/Verisimilitude11/DNAnalyzer/issues/19). It would be great if you provide some description to that. I'll have at other issues in the backlog and pick what I can help with. I will comment under each task separately.

**Comment by chxtio** [comment]
@Verisimilitude11 Hi, is this issue available to work on? If it is, I'm interested in being assigned

**Comment by Verisimilitude11** [comment]
Yes, it is @chxtio. I assigned it to you. By the way would you be interested in joining our Discord server? The link is here: https://github.com/Verisimilitude11/DNAnalyzer/discussions/256

**Comment by LimesKey** [comment]
Perhaps @ImpossibleReality could incorporate this in #289?

**Comment by Verisimilitude11** [comment]
> Perhaps @ImpossibleReality could incorporate this in #289?

No, this issue isn't related to #289 so it would make more sense to open a separate PR for this. @chxtio do you need any help with this issue? You can just use a for loop to accomplish this.

**Comment by LimesKey** [comment]
This is related to the processing of the inputted file, the processing would occur when translating the file from .fasta to .fab. 

I believe how ImpossibleReality is doing it, it can be easily implemented in the conversion rather than a seperate process converting the letters.

**Comment by Verisimilitude11** [comment]
This isn't related to the processing of the inputted file; it is for outputting the RNA version of the DNA if and only if the user specifies via command-line arguments.

DNAnalyzer only analyzes DNA - not RNA. Instead, if you've looked at the code, you'll find that even if the user inputs a sequence of RNA, it converts that to DNA and does the analysis.

**Comment by LimesKey** [comment]
Got it

**Comment by chxtio** [comment]
@Verisimilitude11 Just saw your comment. Let me hop on the discord in a bit

**Comment by Verisimilitude11** [comment]
> @Verisimilitude11 Just saw your comment. Let me hop on the discord in a bit

Sounds great!

**Comment by Verisimilitude11** [comment]
@chxtio just checking in - how far are you on this issue?

**Comment by chxtio** [comment]
@Verisimilitude11 Hi, not much yet. I plan on resuming after my finals are over (after Sun). Sorry for the delay

**Comment by Verisimilitude11** [comment]
@chxtio Alright, sounds like a great plan. Good luck on your finals!

**Comment by Verisimilitude11** [comment]
Hi there,

I hope this message finds you well. I noticed that it has been over a month since you last contributed to the DNAnalyzer project, and I wanted to check in with you to see if you are still interested in being a part of the team.

If you are still interested in working on DNAnalyzer, please let me know and we can discuss how you can get re-involved with the project. If you are no longer interested, I understand and will unassign you from the project for now. However, if you change your mind and want to get involved again in the future, please don't hesitate to reach out – I'll be happy to add you back to the team.

Thank you for your previous contributions to DNAnalyzer, and I hope to hear back from you soon.

Best,
@Verisimilitude11
